export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"66a1919115ac540018708a54",
				"66a1919115ac540018708a57",
				"66a276e72fc7070018ba3895",
				"66ec36b828b5e30023ac92b6"
			]
		},
		"66a1919115ac540018708a54": {
			"id": "66a1919115ac540018708a54",
			"name": "404",
			"pageUrl": "404"
		},
		"66a1919115ac540018708a57": {
			"id": "66a1919115ac540018708a57",
			"name": "index",
			"pageUrl": "index"
		},
		"66a276e72fc7070018ba3895": {
			"id": "66a276e72fc7070018ba3895",
			"pageUrl": "demos",
			"name": "demos"
		},
		"66ec36b828b5e30023ac92b6": {
			"id": "66ec36b828b5e30023ac92b6",
			"pageUrl": "promotionalservices",
			"name": "promotionalservices"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {
			"font": "--headline3"
		},
		"seo": {
			"title": "XZ1 Recordings - Music from the next generation",
			"description": "A single only label for upcoming artists! ",
			"robotsFileType": "autogenerated",
			"favicon_32px": "https://uploads.quarkly.io/66a1919115ac540018708a4f/images/music-player-fill.svg?v=2024-07-25T02:04:54.440Z",
			"customSitemapDomain": "https://xz1label.l5.ca",
			"sitemapFileType": "autogenerated"
		}
	}
}