export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"66a1919115ac540018708a54",
				"66a1919115ac540018708a57"
			]
		},
		"66a1919115ac540018708a54": {
			"id": "66a1919115ac540018708a54",
			"name": "404",
			"pageUrl": "404"
		},
		"66a1919115ac540018708a57": {
			"id": "66a1919115ac540018708a57",
			"name": "index",
			"pageUrl": "index"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {
			"font": "--headline3"
		},
		"seo": {
			"title": "XZ1 Recordings - Powered by one artist",
			"description": "A single only label for upcoming artists! ",
			"robotsFileType": "autogenerated",
			"favicon_32px": "https://uploads.quarkly.io/66a1919115ac540018708a4f/images/music-player-fill.svg?v=2024-07-25T02:04:54.440Z",
			"customSitemapDomain": "https://xz1label.l5.ca"
		}
	}
}